name: Build php-fpm multiarch container

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin    
      - name: build alpine image
        run: |
          docker buildx build -f Dockerfile.alpine --push \
          --tag ginvoicing/php:8.3-fpm-alpine  \
          --platform linux/amd64,linux/arm64 \
          .
      - name: build the image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled && \
          docker buildx build --push \
          --tag ginvoicing/php:8.3-fpm \
          --platform linux/amd64,linux/arm64 \
          .